version: '3.3'

services:
  phoenix:
    image: phoenix-api-base
    command: mix phx.server
    environment:
      - MIX_ENV=dev
    ports:
        - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:10.2
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: 